apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-backend
  template:
    metadata:
      labels:
        app: youtube-backend
    spec:
      containers:
      - name: backend
        image: REPLACE_ME_IMAGE_URL
        imagePullPolicy: Always
        env:
          - name: SPOTIFY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: SPOTIFY_CLIENT_ID
          - name: SPOTIFY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: SPOTIFY_CLIENT_SECRET
          - name: YOUTUBE_API_KEY
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: YOUTUBE_API_KEY
        ports:
        - containerPort: 8080
        resources:
          # t3.micro (1GB RAM)
          limits:
            memory: "512Mi"
            cpu: "800m"
          requests:
            memory: "256Mi"
            cpu: "200m"