apiVersion: v1
kind: Service
metadata:
  name: youtube-frontend-service
spec:
  type: NodePort
  selector:
    app: youtube-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081 # Exposed port for the frontend
