apiVersion: v1
kind: Service
metadata:
  name: youtube-backend-service
spec:
  type: NodePort
  selector:
    app: youtube-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 # Access the outside world through this port.